name: Scoreboard-revision
author: HelloitsRien
version: R4 1.1 RELEASE
main: rien.bijl.Scoreboard.r.Main
description: Lightweight nonflickering scoreboard revision
api-version: 1.20
softdepend: [PlaceholderAPI]
commands:
  sb:
    description: Scoreboard main command